//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dan_XLIX_Nemanja_Pilipovic.Models
{
    public interface IUser
    {
        string Name { get; set; }
        string Surname { get; set; }
        string Mail { get; set; }
        string Username { get; set; }
        string HashedPassword { get; set; }

    }
}