//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dan_XLIX_Nemanja_Pilipovic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAbsence
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FirstDay { get; set; }
        public Nullable<System.DateTime> LastDay { get; set; }
        public string Cause { get; set; }
        public Nullable<int> FkStaff { get; set; }
    
        public virtual tblStaff tblStaff { get; set; }
    }
}
