//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dan_XLIX_Nemanja_Pilipovic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManager : IUser
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Mail { get; set; }
        public string Username { get; set; }
        public string HashedPassword { get; set; }
        public Nullable<int> HotelLevel { get; set; }
        public Nullable<int> YearsOfExperience { get; set; }
        public Nullable<int> QualificationLevel { get; set; }
    }
}
